# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 18 image as a build environment
FROM node:18 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies (ignoring scripts for now to avoid premature builds)
RUN npm install --ignore-scripts

# Copy the rest of the source files
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a slim Node.js image for production
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy the build output and node_modules from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Expose any necessary ports (default MySQL port)
EXPOSE 3306

# Define environment variables for MySQL (can be overridden by user)
ENV MYSQL_HOST=127.0.0.1
ENV MYSQL_PORT=3306
ENV MYSQL_USER=root
ENV MYSQL_PASS=
ENV MYSQL_DB=your_database

# Set the entry point to the built server file
ENTRYPOINT ["node", "dist/index.js"]
